import {
  WarehouseProfile,
  SetupChecklist,
  RouteItem,
  ScanSummary,
  EarningsSummary,
  RateCard,
} from "./types";

export const WARP_MARKETS = [
  "LAX — Los Angeles",
  "SFO — San Francisco",
  "SAN — San Diego",
  "PHX — Phoenix",
  "DFW — Dallas-Fort Worth",
  "IAH — Houston",
  "ATL — Atlanta",
  "MIA — Miami",
  "EWR — Newark / NYC",
  "ORD — Chicago",
  "SEA — Seattle",
  "DEN — Denver",
  "IND — Indianapolis",
  "CLT — Charlotte",
  "BNA — Nashville",
];

export const DEFAULT_RATE_CARD: RateCard = {
  palletIn: 8.5,
  palletOut: 8.5,
  storagePerDay: 3.0,
  effectiveDate: "2026-07-01",
};

export const EMPTY_WAREHOUSE: WarehouseProfile = {
  id: "",
  name: "",
  companyName: "",
  contactName: "",
  phone: "",
  email: "",
  address: { street: "", city: "", state: "", zip: "" },
  nearestMarket: "",
  facility: {
    sqft: null,
    dockDoors: null,
    fullTimeEmployees: null,
    storageType: "",
    afterHoursWilling: false,
    afterHoursFee: null,
    holidayWilling: false,
    holidayFee: null,
  },
  operatingHours: [
    { day: "Monday", isOpen: true, fromTime: "06:00", toTime: "18:00" },
    { day: "Tuesday", isOpen: true, fromTime: "06:00", toTime: "18:00" },
    { day: "Wednesday", isOpen: true, fromTime: "06:00", toTime: "18:00" },
    { day: "Thursday", isOpen: true, fromTime: "06:00", toTime: "18:00" },
    { day: "Friday", isOpen: true, fromTime: "06:00", toTime: "18:00" },
    { day: "Saturday", isOpen: false, fromTime: "06:00", toTime: "14:00" },
    { day: "Sunday", isOpen: false, fromTime: "", toTime: "" },
  ],
  capabilities: {
    ltlCrossDock: false,
    outsideSoftware: false,
    transload: false,
  },
  techReadiness: {
    hasDevices: null,
    hasLabelPrinter: null,
    hasFloorInternet: null,
  },
  onboardingStatus: "draft",
  onboardingStep: 0,
  createdAt: new Date().toISOString(),
};

export const EMPTY_SETUP: SetupChecklist = {
  rateTermsAccepted: false,
  rateTermsAcceptedAt: null,
  trainingScheduled: false,
  mobileAppInstalled: false,
  desktopAppInstalled: false,
  testScanInCompleted: false,
  testScanOutCompleted: false,
  labelPrintTestPassed: false,
  goLiveRequested: false,
  goLiveRequestedAt: null,
};

export const MOCK_ROUTES: RouteItem[] = [
  {
    id: "01HYXZ1234",
    shipmentCode: "SHP-28401",
    direction: "inbound",
    status: "In Transit to Warehouse",
    origin: "Phoenix, AZ",
    destination: "WTCH-LAX-9",
    palletCount: 6,
    eta: "Today 2:30 PM",
    carrierName: "Southwest Express",
  },
  {
    id: "01HYXZ1235",
    shipmentCode: "SHP-28402",
    direction: "inbound",
    status: "Arrived at Warehouse",
    origin: "Las Vegas, NV",
    destination: "WTCH-LAX-9",
    palletCount: 4,
    eta: "Arrived 11:15 AM",
    carrierName: "Desert Haul Inc",
  },
  {
    id: "01HYXZ1236",
    shipmentCode: "SHP-28410",
    direction: "outbound",
    status: "Ready for Pickup",
    origin: "WTCH-LAX-9",
    destination: "San Diego, CA",
    palletCount: 8,
    eta: "Pickup 4:00 PM",
    carrierName: "Pacific Coast Freight",
  },
  {
    id: "01HYXZ1237",
    shipmentCode: "SHP-28411",
    direction: "outbound",
    status: "Departed",
    origin: "WTCH-LAX-9",
    destination: "Bakersfield, CA",
    palletCount: 3,
    eta: "Departed 9:45 AM",
    carrierName: "Valley Logistics",
  },
  {
    id: "01HYXZ1238",
    shipmentCode: "SHP-28415",
    direction: "inbound",
    status: "In Transit to Warehouse",
    origin: "Fresno, CA",
    destination: "WTCH-LAX-9",
    palletCount: 10,
    eta: "Today 5:00 PM",
    carrierName: "Central Cal Transport",
  },
];

export const MOCK_SCANS: ScanSummary = {
  period: "Jun 22 – Jun 28, 2026",
  totalInbound: 72,
  scannedInbound: 69,
  totalOutbound: 68,
  scannedOutbound: 68,
  missedScans: [
    {
      shipmentCode: "SHP-28320",
      direction: "inbound",
      palletId: "PLT-9981",
      arrivalTime: "Jun 24, 3:12 PM",
    },
    {
      shipmentCode: "SHP-28321",
      direction: "inbound",
      palletId: "PLT-9982",
      arrivalTime: "Jun 24, 3:12 PM",
    },
    {
      shipmentCode: "SHP-28345",
      direction: "inbound",
      palletId: "PLT-10023",
      arrivalTime: "Jun 26, 11:40 AM",
    },
  ],
};

export const MOCK_EARNINGS: EarningsSummary = {
  period: "Jun 22 – Jun 28, 2026",
  palletsIn: 69,
  palletsOut: 68,
  avgDailyStorageCount: 6,
  storageDays: 42, // 6 pallets/day × 7 days
  afterHoursOpens: 2,
  ratePerPalletIn: 8.5,
  ratePerPalletOut: 8.5,
  ratePerStorageDay: 3.0,
  ratePerAfterHours: 150.0, // dock-set example rate
  totalEarned: 69 * 8.5 + 68 * 8.5 + 42 * 3.0 + 2 * 150.0,
  paymentStatus: "processing",
};

export const MOCK_EARNINGS_HISTORY: EarningsSummary[] = [
  MOCK_EARNINGS,
  {
    period: "Jun 15 – Jun 21, 2026",
    palletsIn: 85,
    palletsOut: 82,
    avgDailyStorageCount: 5.4,
    storageDays: 38,
    afterHoursOpens: 1,
    ratePerPalletIn: 8.5,
    ratePerPalletOut: 8.5,
    ratePerStorageDay: 3.0,
    ratePerAfterHours: 150.0,
    totalEarned: 85 * 8.5 + 82 * 8.5 + 38 * 3.0 + 1 * 150.0,
    paymentStatus: "paid",
  },
  {
    period: "Jun 8 – Jun 14, 2026",
    palletsIn: 78,
    palletsOut: 75,
    avgDailyStorageCount: 4.3,
    storageDays: 30,
    afterHoursOpens: 0,
    ratePerPalletIn: 8.5,
    ratePerPalletOut: 8.5,
    ratePerStorageDay: 3.0,
    ratePerAfterHours: 150.0,
    totalEarned: 78 * 8.5 + 75 * 8.5 + 30 * 3.0 + 0,
    paymentStatus: "paid",
  },
];
